[package]
name = "adbf_rs"
version = "0.1.0"
authors = ["tul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version="^0.4"}
encoding_rs = {version="^0.8"}
futures = {version="^0.3"}